package com.kuky.base.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.kuky.base.db_entity.Order;
import com.kuky.base.db_entity.User;
import com.kuky.base.db_entity.Hobby;

import com.kuky.base.greendao.OrderDao;
import com.kuky.base.greendao.UserDao;
import com.kuky.base.greendao.HobbyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig orderDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig hobbyDaoConfig;

    private final OrderDao orderDao;
    private final UserDao userDao;
    private final HobbyDao hobbyDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        hobbyDaoConfig = daoConfigMap.get(HobbyDao.class).clone();
        hobbyDaoConfig.initIdentityScope(type);

        orderDao = new OrderDao(orderDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        hobbyDao = new HobbyDao(hobbyDaoConfig, this);

        registerDao(Order.class, orderDao);
        registerDao(User.class, userDao);
        registerDao(Hobby.class, hobbyDao);
    }
    
    public void clear() {
        orderDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        hobbyDaoConfig.clearIdentityScope();
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public HobbyDao getHobbyDao() {
        return hobbyDao;
    }

}
